; Rattboy's Ploybar config file
;
; This is for my 2 monitor (Old LG Flatron and Koobi Gamiing monitor) setup on my Intel NUC 
;
; Dependencies
; Font: Hack Nerd Font - You can get this via https://www.nerdfonts.com/font-downloads
; Font: Weather Icons - You can get this via the AUR
; Python-pywal - You can get this via pacman
; openweathermap.org ARI Key - Follow the step via https://openweathermap.org/appid
; picom - You can get this via pacman
; Kalendar - You can get this via pacman
;

[colors]

;###############
;## For pywal ##
;###############

foreground = ${xrdb:foreground:#f3f4f5}
background = ${xrdb:background:#2f343f}

black       = ${xrdb:color0:#1d2021}
darkred     = ${xrdb:color1:#cc241d}
darkgreen   = ${xrdb:color2:##0f8548}
darkyellow  = ${xrdb:color3:#d79921}
darkblue    = ${xrdb:color4:#255ea1}
darkmagenta = ${xrdb:color5:#b16286}
darkcyan    = ${xrdb:color6:#609996}
grey        = ${xrdb:color7:#59646b}

lightgray   = ${xrdb:color8:#8f9da6}
red         = ${xrdb:color9:#e53935}
green       = ${xrdb:color10:#2cd179}
yellow      = ${xrdb:color11:#ffc85e}
blue        = ${xrdb:color12:#5294e2}
darkpurple  = ${xrdb:color13:#e86ba4}
cyan        = ${xrdb:color14:#68d4ce}
white       = ${xrdb:color15:#f3f4f5}

[bar/bar]
monitor = ${env:MONITOR:DP-1}
width = 100%
height = 24pt
radius = 6

background = ${colors.background}
foreground = ${colors.foreground}


line-size = 3pt

border-size = 4pt
border-color = #00000000

padding-left = 0
padding-right = 1

module-margin = 1

separator = " " 
separator-foreground = ${colors.grey}

font-0 = "HackNerdFont:style=Solid:size=11;2"
font-1 = Weather Icons:size=12;1
font-2 = NotoColorEmoji:fontformat=truetype:scale=10:antialias=false;
font-3 = MaterialIcons:size=19

modules-left = xworkspaces ciderbar
modules-right = pulseaudio memory cpu wlan arch-aur-updates wired-network weather clickdate

cursor-click = pointer
cursor-scroll = ns-resize

enable-ipc = true

wm-restack = i3

;#############
;## Modules ##
;#############

;##########
;## Left ##
;##########

[module/xworkspaces]
type = internal/xworkspaces

label-active = %name%
label-active-background = ${colors.blue}
label-active-underline= ${colors.red}
label-active-padding = 1

label-occupied = %name%
label-occupied-padding = 1

label-urgent = %name%
label-urgent-background = ${colors.alert}
label-urgent-padding = 1

label-empty = %name%
label-empty-foreground = ${colors.grey}
label-empty-padding = 1

[module/ciderbar]
type = custom/script
exec = cider-polybar -a get-currentmediaitem
scroll-up = cider-polybar -a volume -v 0.01
scroll-down = cider-polybar -a volume -v -0.01
interval = 0.3

;[module/xwindow]
;type = internal/xwindow
;label = %title:0:60:...%

;###########
;## Right ##
;###########

[module/arch-aur-updates]
type = custom/script
exec = /home/kris/.config/polybar/scripts/check-all-updates.sh
interval = 1000
label =  %output%
format-prefix = "󰏗"
format-prefix-foreground = ${colors.darkyellow}
format-background = ${colors.background}
format-underline = ${colors.darkyellow}
format-margin = 2
format-padding = 0

[module/aur-updates]
type = custom/script
exec = cower -u | wc -l
interval = 1000
label = Aur: %output%
format-foreground = ${colors.foreground}
format-background = ${colors.background}
format-prefix = "🗘 "
format-prefix-foreground = #${colors.darkyellow}
format-underline = ${colors.red}

[module/cpu-usage]
type = custom/script
exec = polycpu
label = "%output%"
ckick-left = %{A1:alacrity -e htop:}
interval = 10
format-prefix = "💻 "

[module/pulseaudio]
type = internal/pulseaudio
format-volume-prefix = " "
format-volume-prefix-foreground = ${colors.darkyellow}
format-volume = <label-volume>
label-volume = %percentage%%
label-muted = muted
label-muted-foreground = ${colors.grey}

[module/memory]
type = internal/memory
interval = 2
format-prefix = "󰍛 "
format-prefix-foreground = ${colors.darkyellow}
label = %percentage_used:2%%

[module/cpu]
type = internal/cpu
interval = 2
format-prefix = "󰍹 "
format-prefix-foreground = ${colors.darkyellow}
label = %{A1:alacritty -e htop:}%percentage:2%%%{A}

[module/wlan]
type = internal/network
interval = 5
interface-type = wireless
format-conected = <label-connected>
label-connected = %local_ip%

[module/wired-network]
type = internal/network
interval = 5
format-prefix = "󰈀"
format-prefix-foreground = ${colors.darkyellow}
interface = enp0s25
format-conected = <label-connected>
label-connected = %linkspeed%

[module/weather]
type = custom/script
exec = /home/kris/.config/polybar/scripts/weather.sh
tail = false
interval = 960
label-font = 2

[module/clickdate]
type = custom/script
format-prefix =    
format-prefix-foreground = ${colors.darkyellow}
exec = date +'  %A, %B %d. %H:%M:%S'
tail = false
interval = 1
click-left = kalendar

;These are the most common formatting characters for the date command:

;%D – Display date as mm/dd/yy
;%Y – Year (e.g., 2020)
;%m – Month (01-12)
;%B – Long month name (e.g., November)
;%b – Short month name (e.g., Nov)
;%d – Day of month (e.g., 01)
;%j – Day of year (001-366)
;%u – Day of week (1-7)
;%A – Full weekday name (e.g., Friday)
;%a – Short weekday name (e.g., Fri)
;%H – Hour (00-23)
;%I – Hour (01-12)
;%M – Minute (00-59)
;%S – Second (00-60)

[settings]
screenchange-reload = true
pseudo-transparency = true

; vim:ft=dosini
