; ####################################
; ##  Rattboy's Polybar config file ##
; ####################################
;
; This is for my 2 monitor (Old LG Flatron and Koorui Gamiing monitor) setup on my Intel NUC;
; Dependencies
; Font: Hack Nerd Font - You can get this via https://www.nerdfonts.com/font-downloads
; Font: Weather Icons - You can get this via the AUR
; Font: DejaVu Sans Mono wifi ramp
; Python-pywal - You can get this via pacman
; openweathermap.org ARI Key - Follow the step via https://openweathermap.org/appid
; picom - You can get this via pacman
; Kalendar - You can get this via pacman
;

[colors]

;###############
;## For pywal ##
;###############

foreground = ${xrdb:foreground:#f3f4f5}
background = ${xrdb:background:#2f343f}

black       = ${xrdb:color0:#1d2021}
darkred     = ${xrdb:color1:#cc241d}
darkgreen   = ${xrdb:color2:##0f8548}
darkyellow  = ${xrdb:color3:#d79921}
darkblue    = ${xrdb:color4:#255ea1}
darkmagenta = ${xrdb:color5:#b16286}
darkcyan    = ${xrdb:color6:#609996}
grey        = ${xrdb:color7:#59646b}

lightgray   = ${xrdb:color8:#8f9da6}
red         = ${xrdb:color9:#e53935}
green       = ${xrdb:color10:#2cd179}
yellow      = ${xrdb:color11:#ffc85e}
blue        = ${xrdb:color12:#5294e2}
darkpurple  = ${xrdb:color13:#e86ba4}
cyan        = ${xrdb:color14:#68d4ce}
white       = ${xrdb:color15:#f3f4f5}

[bar/bar]
monitor = ${env:MONITOR:DP-1}
width = 100%
height = 24pt
radius = 6

background = ${colors.background}
foreground = ${colors.foreground}


line-size = 3pt

border-size = 4pt
border-color = #00000000

padding-left = 0
padding-right = 1

module-margin = 1

separator = " "
separator-foreground = ${colors.grey}

font-0 = HackNerdFont:style=Solid:size=11;2
font-1 = DejaVu Sans Mono wifi ramp:size=10
font-2 = Weather Icons:size=12;1
font-3 = MaterialIcons:size=19

modules-left = i3 ciderbar 
modules-right = pulseaudio wlan lan weather date time
format-underline = ${colors.darkyellow}

cursor-click = pointer
cursor-scroll = ns-resize

enable-ipc = true

wm-restack = i3

;#############
;## Modules ##
;#############

[module/i3]
type = internal/i3

; Default: false
pin-workspaces = true

; Default: false
strip-wsnumbers = false

; Default: false
index-sort = false

; Default: true
enable-click = true

; Default: true
enable-scroll = true

; Default: true
wrapping-scroll = false

; Default: true
reverse-scroll = false

; Default: false
fuzzy-match = false

ws-icon-0 = 1;󰅥 
ws-icon-1 = 2;
ws-icon-2 = 3;
ws-icon-3 = 4;
ws-icon-4 = 5; 
ws-icon-5 = 6;
ws-icon-6 = 7;
ws-icon-7 = 8;
ws-icon-8 = 9;
ws-icon-9 = 10;
ws-icon-default = " "

format = <label-state> <label-mode>

label-mode = %mode%
label-mode-padding = 2
label-mode-foreground = #000000
label-mode-background = #FFBB00

; focused = Active workspace on focused monitor
label-focused = %icon% %name%
label-focused-background = ${colors.background}
label-focused-foreground = ${colors.foreground}
label-focused-underline = #AD69AF
label-focused-padding = 2

; unfocused = Inactive workspace on any monitor
label-unfocused = %icon% %name%
label-unfocused-padding = 2
label-unfocused-background = ${colors.background}
label-unfocused-foreground = ${colors.foreground}
label-unfocused-underline =

; visible = Active workspace on unfocused monitor
label-visible = %icon% %name%
label-visible-background = ${self.label-focused-background}
label-visible-underline = ${self.label-focused-underline}
label-visible-padding = 2

; urgent = Workspace with urgency hint set
label-urgent = %icon% %name%
label-urgent-background = ${self.label-focused-background}
label-urgent-foreground = #db104e
label-urgent-padding = 2

format-foreground = ${colors.foreground}
format-background = ${colors.background}

[module/xworkspaces]
type = internal/xworkspaces

label-active = %name%
label-active-background = ${colors.blue}
label-active-underline= ${colors.red}
label-active-padding = 1

label-occupied = %name%
label-occupied-padding = 1

label-urgent = %name%
label-urgent-background = ${colors.alert}
label-urgent-padding = 1

label-empty = %name%
label-empty-foreground = ${colors.grey}
label-empty-padding = 1

[module/ciderbar]
type = custom/script
exec = cider-polybar -a get-currentmediaitem
scroll-up = cider-polybar -a volume -v 0.01
scroll-down = cider-polybar -a volume -v -0.01
interval = 0.3

[module/pacman-updates]
type = custom/script
exec = checkupdates | wc -l
initial =1000
format-prefix = "󰮯 "
format-prefix-foreground = ${colors.darkyellow}
label = %{A1:alacritty -e sudo pacman -Syu:}%output%%{A}
font = 1
format-background = ${colors.background}

[module/aur-updates]
type = custom/script
exec = yay -Qum | wc -l
initial =1000
format-prefix = " "
format-prefix-foreground = ${colors.darkyellow}
label = %{A1:alacritty -e yay -Syu:}%output%%{A}
font = 1
format-background = ${colors.background}

[module/pulseaudio]
type = internal/pulseaudio
format-volume-prefix = " "
format-volume-prefix-foreground = ${colors.darkyellow}
format-volume = <label-volume>
label-volume = %percentage%%
label-muted = 󰖁 muted
label-muted-foreground = ${colors.grey}

[module/weather]
type = custom/script
exec = /home/kris/.config/polybar/scripts/weather.sh
tail = false
interval = 960
label-font = 3

[module/date]
type = custom/script
format-prefix = 
format-prefix-foreground = ${colors.darkyellow}
exec = date +' %A, %B %d %Y'
tail = false
interval = 1
click-left = kalendar

[module/time]
type = internal/date
interval = 1
format-prefix = "󰥔 " 
format-prefix-foreground = ${colors.darkyellow}
time =  %H:%M:%S
time-alt =  %I:%M:%S %p
label =  %time%


[module/lan]
type = internal/network
interface = enp0s25
interval = 5
accumulate-stats = true
unknown-as-up = true
label-connected = 󰈀  %linkspeed%
label-disconnected = 󱂑
format-connected = %{A1:~/.config/rofi-network-manager/rofi-network-manager.sh:}<label-connected>%{A}
format-disconnected = %{A1:~/.config/rofi-network-manager/rofi-network-manager.sh:}<label-disconnected>%{A}

[module/wlan]
type = internal/network
interface = wlan0
interval = 1.0
accumulate-stats = true
unknown-as-up = true
label-connected = %downspeed:9%
label-disconnected = 
format-connected = %{A1:~/.config/rofi-network-manager/rofi-network-manager.sh:}<ramp-signal> <label-connected>%{A}
format-disconnected = %{A1:~/.config/rofi-network-manager/rofi-network-manager.sh:}<label-disconnected>%{A}
format-disconnected-foreground = ${colors.darkyellow}
ramp-signal-0 = 
ramp-signal-1 = 
ramp-signal-2 = 
ramp-signal-3 = 
ramp-signal-4 = 
ramp-signal-5 = 

[settings]
screenchange-reload = true
pseudo-transparency = true

; vim:ft=dosini
